apiVersion: v1
kind: ServiceAccount
metadata:
  name: deviceservice-sa
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "deviceservice-role"
rules:
- apiGroups: ["stable.example.com"]
  resources: ["crontabs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: 'rbac.authorization.k8s.io/v1'
kind: 'ClusterRoleBinding'
metadata:
  name: 'deviceservice-binding'
  namespace: default
roleRef:
  apiGroup: ''
  kind: 'ClusterRole'
  name: 'deviceservice-role'
subjects:
  - kind: 'ServiceAccount'
    name: 'deviceservice-sa'
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deviceservice
  name: deviceservice
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deviceservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deviceservice
    spec:
      serviceAccountName: 'deviceservice-sa'
      containers:
      - image: ghcr.io/johnsonshih/deviceservice:v1
        imagePullPolicy: Always
        name: deviceservice
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
          - name: ONVIF_SECRET_DIRECTORY
            value: /etc/onvif-secret-volume
        volumeMounts:
          - name: secret-volume
            mountPath: /etc/onvif-secret-volume
            readOnly: true

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: secret-volume
          secret:
            secretName: onvif-auth-secret
