---
# Source: akri/templates/onvif-discovery-handler.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: akri-onvif-discovery-daemonset
  labels:
    helm.sh/chart: akri-0.12.19
    app.kubernetes.io/part-of: akri
    app.kubernetes.io/instance: akri-onvif-dh
    app.kubernetes.io/version: "0.12.19"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: akri-onvif-discovery
    app.kubernetes.io/component: discovery-handler
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: akri
      app.kubernetes.io/instance: akri-onvif-dh
      app.kubernetes.io/name: akri-onvif-discovery
  template:
    metadata:
      labels:
        helm.sh/chart: akri-0.12.19
        app.kubernetes.io/part-of: akri
        app.kubernetes.io/instance: akri-onvif-dh
        app.kubernetes.io/version: "0.12.19"
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: akri-onvif-discovery
        app.kubernetes.io/component: discovery-handler
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: akri-onvif-discovery
        image: "ghcr.io/johnsonshih/akri/onvif-discovery:v0.12.12-20240111_215504"
        resources:
          requests:
            memory: 11Mi
            cpu: 10m
          limits:
            memory: 24Mi
            cpu: 24m
        env:
        - name: DISCOVERY_HANDLERS_DIRECTORY
          value: /var/lib/akri
        volumeMounts:
        - name: discovery-handlers
          mountPath: /var/lib/akri
      nodeSelector:
        "kubernetes.io/os": linux
      volumes:
      - name: discovery-handlers
        hostPath:
          path: /var/lib/akri
