---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-d
  namespace: default
data:
  nginx.conf: |+
    events { }

    http {

      server {
        listen 80;

        location /flask {
          proxy_pass http://192.168.1.145:8080/api/v1/helloworld;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        testService: service-1
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config-d
          mountPath: /etc/nginx
      volumes:
      - name: nginx-config-d
        configMap:
          name: nginx-config-d
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
    testService: service-1
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30081
