---
apiVersion: v1
kind: Secret
metadata:
  name: onvif-auth-secret
type: Opaque
stringData:
  3fa1fe68_b915_4053_a3e1_ac15a21f5f91_username: camuser
  3fa1fe68_b915_4053_a3e1_ac15a21f5f91_password: HappyDay!

